from PyQt5.QtWidgets import QPushButton, QWidget

buttons = []
one = QPushButton("1")
buttons.append(one)
two = QPushButton("2")
buttons.append(two)
three = QPushButton("3")
buttons.append(three)
four = QPushButton("4")
buttons.append(four)
five = QPushButton("5")
buttons.append("5")
six = QPushButton("6")
buttons.append(six)
seven = QPushButton("7")
buttons.append(seven)
eight = QPushButton("8")
buttons.append(eight)
nine = QPushButton("9")
buttons.append(nine)
zero = QPushButton("0")
buttons.append("0")

print(buttons)
